% CPMG 1D sequence
% Wells running along z, slice select in x, readout in z
% Converted from Python pypulseq

%% Parameters
slice_thickness   = 4e-3;
n_slices          = 8;
num_pts           = 32;
fov               = 50e-3;
delta_k           = 1 / fov;
t_echo            = 10e-3;
num_echoes        = 3;
exc_pulse_duration   = 2.5e-3;
refoc_pulse_duration = 2e-3;
grad_rise_time    = 110e-6;

%% System limits
system = mr.opts( ...
    'MaxGrad',        32, ...
    'GradUnit',       'mT/m', ...
    'MaxSlew',        130, ...
    'SlewUnit',       'T/m/s', ...
    'rfRingdownTime', 30e-6, ...
    'rfDeadTime',     100e-6, ...
    'adcDeadTime',    10e-6 ...
);

%% Sequence object
seq = mr.Sequence(system);

%% Excitation pulse + slice-select gradient (x)
time_bw_product = 4;

[rf, ~] = mr.makeSincPulse( ...
    pi/2, ...
    'Duration',        exc_pulse_duration, ...
    'SliceThickness',  slice_thickness, ...
    'Apodization',     0.42, ...
    'TimeBwProduct',   time_bw_product, ...
    'system',          system, ...
    'delay',           system.rfDeadTime, ...
    'use',             'excitation' ...
);

bandwidth = time_bw_product / exc_pulse_duration;   % Hz
amplitude = bandwidth / slice_thickness;            % Hz/m

gx = mr.makeTrapezoid( ...
    'x', ...
    'Amplitude',  amplitude, ...
    'RiseTime',   grad_rise_time, ...
    'FlatTime',   exc_pulse_duration, ...
    'system',     system ...
);

%% Readout gradient (z) and pre-winders
gz_dur           = t_echo - refoc_pulse_duration - 2*system.rfDeadTime;
reph_grad_duration = (t_echo - exc_pulse_duration - refoc_pulse_duration) / 2 ...
                     - grad_rise_time - system.rfDeadTime;

gz = mr.makeTrapezoid( ...
    'z', ...
    'Area',      num_pts * delta_k, ...
    'Duration',  gz_dur, ...
    'RiseTime',  grad_rise_time, ...
    'system',    system ...
);

gz_prewind = mr.makeTrapezoid( ...
    'z', ...
    'Area',      gz.area / 2, ...
    'Duration',  reph_grad_duration, ...
    'RiseTime',  grad_rise_time, ...
    'system',    system ...
);

gx_reph = mr.makeTrapezoid( ...
    'x', ...
    'Area',      -gx.area / 2, ...
    'Duration',  reph_grad_duration, ...
    'RiseTime',  grad_rise_time, ...
    'system',    system ...
);

%% Refocusing pulse (180 deg block pulse, phase = 90 deg)
rf180 = mr.makeBlockPulse( ...
    pi, ...
    'Duration',     refoc_pulse_duration, ...
    'system',       system, ...
    'delay',        system.rfDeadTime, ...
    'PhaseOffset',  pi/2, ...
    'use',          'refocusing' ...
);

%% ADC
adc_raster = system.adcRasterTime;
dwell      = round(gz.flatTime / num_pts / adc_raster) * adc_raster;
duration   = dwell * num_pts;

adc = mr.makeAdc( ...
    num_pts, ...
    'Duration', duration, ...
    'Delay',    grad_rise_time, ...   % start sampling when gradient is flat
    'system',   system ...
);

%% Build sequence
seq.addBlock(rf, gx);
seq.addBlock(gx_reph, gz_prewind);

for i = 1:num_echoes
    seq.addBlock(rf180);
    seq.addBlock(mr.makeDelay(system.rfDeadTime - system.rfRingdownTime));
    seq.addBlock(gz, adc);
end

%% Check and write
seq.checkTiming();
seq.write('cpmg_1d.seq');
disp("Done!")
